tintoy/msbuild-project-tools-server

src/LanguageServer.Common/Utilities/MSBuildHelper.cs, src/LanguageServer.Engine/Configuration.cs, src/LanguageServer.Engine/Documents/MasterProjectDocument.cs, src/LanguageServer.Engine/Documents/ProjectDocument.cs
tintoy/msbuild-project-tools-vscode#35
=> Enable per-workspace override of MSBuildExtensionsPath.

src/LanguageServer.Common/Utilities/MSBuildHelper.cs
related on tintoy/msbuild-project-tools-vscode#46
=> fix toolsversion related exception when using dotnet-sdk3.

src/LanguageServer.Engine/CompletionProviders/TaskElementCompletion.cs, src/LanguageServer.Engine/CompletionProviders/TopLevelElementCompletion.cs
This makes the snippets work much nicer with indentations other than 4 spaces.
=> Use tab-character in completion text

src/LanguageServer.Common/Utilities/MSBuildHelper.cs
With this change, the version number doesn't have to be updated when new versions of 2.1.5xx ship, which is used by VS 2017.
=> Recognize future versions of the .NET Core SDK 2.1.5xx

help/properties.json
Missing properties:
- PublishReadyToRun
- PublishSingleFile
- SelfContained
- PublishTrimmed
- IsTrimmable
- ManagedAssemblyToLink
- TrimMode
- TrimmerRootAssembly
- TrimmerRootDescriptor
- SuppressTrimAnalysisWarnings
- ILLinkWarningLevel
- ILLinkTreatWarningsAsErrors
- TrimmerRemoveSymbols
- DebuggerSupport
- EnableUnsafeBinaryFormatterSerialization
- EnableUnsafeUTF7Encoding
- EventSourceSupport
- HttpActivityPropagationSupport
- InvariantGlobalization
- UseSystemResourceKeys
https://docs.microsoft.com/en-us/dotnet/core/deploying/ready-to-run
https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming-options
=> Add ReadyToRun and Single File Deployment related properties

build.ps1, build.sh, docs/BUILDING.md
1. Added `restore` command to building scripts
2. Updated building guides to include information about various ways to debug LSP
=> Update building guide to include ways to debug LSP

src/LanguageServer.TaskReflection/LanguageServer.TaskReflection.csproj, src/LanguageServer.TaskReflection/Program.cs
As far as I know this project started before System.Text.Json was even a thing. At that time using Newtonsoft was kinda s standart for json workloads in .NET ecosystem. However, since now we target .NET 6, the built-in solution now have all capabilities that we need. Therefore I would say it is preferable to use what is given to us out of the box for several reasons:
1. This way the resulting bundle size becomes smaller
2. We don't need to control dependency updates since built-in library automatically updated when we bump target framework version
3. System.Text.Json was designed to be efficient and is considered to be one of the best json libraries form perf perspective
Closes https://github.com/tintoy/msbuild-project-tools-server/pull/30 as no longer relevant
=> Move to built-in System.Text.Json in TaskReflection project

src/LanguageServer.Engine/Documents/Workspace.cs
For context, before #36 code looked like:
```cs
if (MasterProject == null)
return MasterProject = new MasterProjectDocument(this, documentUri, Log);
```
Since 2 people looked at this code and didn't notice behavior change, let's separate assign and return statements for better readability
=> Fix regression introduced in #36

src/LanguageServer.Common/Utilities/MSBuildHelper.cs, src/LanguageServer.Engine/Documents/ProjectDocument.cs, src/LanguageServer.Engine/Documents/Workspace.cs, test/LanguageServer.Engine.Tests/MSBuildTests.cs
Follow up to https://github.com/tintoy/msbuild-project-tools-server/pull/39
This doesn't allow to drop Newtonsoft dependency from `LanguageServer.Common` project, but it moves us forward. This change is even guarded with test, so I am more than sure, that no regressions here.
Also `JsonNode` doesn't have async method for parsing from stream (and it's a bit odd), so several async methods become normal now
=> Move to built-in System.Text.Json API when parsing project assets file

src/LanguageServer.SemanticModel.Xml/LanguageServer.SemanticModel.Xml.csproj
`SemanticModel.Xml` doesn't directly depend on NuGet libraries and never mentions them in its source code. Thus it isn't a good practice to make such "hard dependency" in its project file. At least when time comes we have less places to change for library update
Closes https://github.com/tintoy/msbuild-project-tools-server/pull/45
=> Remove direct Nuget dependency from `SemanticModel.Xml` project

src/LanguageServer.Common/LanguageServer.Common.csproj, src/LanguageServer.SemanticModel.MSBuild/LanguageServer.SemanticModel.MSBuild.csproj, src/LanguageServer.SemanticModel.MSBuild/MSBuildObject.cs, src/LanguageServer/LanguageServer.csproj
Continuation of dependency removal. This time focused specifically on `Microsoft.Language.Xml`. It is only used in `SemanticModel.Xml` and `Engine` projects, other projects don't need it
=> Drop `Microsoft.Language.Xml` dependency from projects, that doesn't use it

src/LanguageServer.Common/LanguageServer.Common.csproj
- `System.Collection.Immutable` -> unused
- `NuGet.Client` -> unused
- `NuGet.PackageManagement` -> replaced with `Nuget.Protocol` since we use only its functionality
- `NuGet.Packaging` -> unused
- `NuGet.Configuration`, `NuGet.Credentials`, `Nuget.Versioning` -> these 3 are dependencies of `NuGet.Protocol`. In order to minimize amount of dependency errors, when 2 different versions of the same library are used let's consume these from `NuGet.Protocol` and don't depend on them directly
Closes https://github.com/tintoy/msbuild-project-tools-server/pull/47
=> Simplify dependency list for `Common` project

help/properties.json, src/LanguageServer.Common/Help/PropertyHelp.cs, src/LanguageServer.Engine/CompletionProviders/PropertyElementCompletionProvider.cs, src/LanguageServer.SemanticModel.MSBuild/MSBuildSchemaHelp.cs
- Imroved default values for well-known `LangVersion` property o include all currently possible values
- Removed concept of single default value since it isn't used now (`LangVersion` was the last property that actually used it) and it has the same effect as list of default values with a single value in it. So don't repeat ourselves)
=> Improve default values for well-known `LangVersion` property and a bit od clean up

test/LanguageServer.Engine.Tests/LanguageServer.Engine.Tests.csproj
Tests should never have explicit dependencies on libraries, used by an actual project. Because if they do there is a chance of dependency versions mismatch leading to false- or true-negative test outcomes
Closes https://github.com/tintoy/msbuild-project-tools-server/pull/49
=> Remove project dependencies from langusge server tests

README.md
Server side of https://github.com/tintoy/msbuild-project-tools-vscode/pull/123
=> Remove mentioning .NET 6 as a requirement for the end user

src/LanguageServer.Engine/CompletionProviders/CommentCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/CompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/ICompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/ItemAttributeCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/ItemElementCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/ItemGroupExpressionCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/ItemMetadataCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/ItemMetadataExpressionCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/PackageReferenceCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/PropertyConditionCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/PropertyElementCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/PropertyExpressionCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/TargetNameCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/TaskElementCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/TaskParameterCompletionProvider.cs, src/LanguageServer.Engine/CompletionProviders/TopLevelElementCompletionProvider.cs
It was only used to enrich context for logging. However, since logger already takes source type as context and every provider has a unique name, I consider it unnecessary. Even if we for whatever reason want to enrich logger with more type-related data, we better use something like `GetType().Name`. Since logs are used to investigate things, having a direct type name there would be better. But again, I don't think that even this thing is necessary since we provide type as context anyway.
@tintoy I would like your approval on this before merging
=> Remove unnecessary `Name` property from completion providers

src/LanguageServer.Engine/CompletionProviders/TaskElementCompletionProvider.cs
Tasks are basically "other function calls" inside a target, so it makes sence to show them as functions
Before:
After:
=> Add completion kind to task elements

src/LanguageServer.Engine/Documents/Workspace.cs, src/LanguageServer/Program.cs
Part of https://github.com/tintoy/msbuild-project-tools-server/issues/72. Now `data` directory is created in the language server's directory and does not depend on `MSBUILD_PROJECT_TOOLS_DIR` environment variable
=> Remove usage of `MSBUILD_PROJECT_TOOLS_DIR` environment variable

.editorconfig, src/Directory.Build.props
1. Put all C#-related options under C# section
2. Since `IDE0016` is controlled via `csharp_style_throw_expression` option, we don't need to supress it wia MsBuild's `NoWarn` property
=> Refactor editorconfig

src/Directory.Build.props
According to [documentation](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#assettargetfallback) `AssertTargetFallback` is required to have a [valid framework identifier](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks). `dnxcore50` isn't a valid TFI AFAICT, so having such property is pointless. However, it somehow got there, so I'm not gonna merge this untill approved
=> Remove assert target fallback

src/LanguageServer.Common/LanguageServer.Common.csproj, src/LanguageServer.Engine/LanguageServer.Engine.csproj, src/LanguageServer.SemanticModel.MSBuild/LanguageServer.SemanticModel.MSBuild.csproj, src/LanguageServer/LanguageServer.csproj
Closes: https://github.com/tintoy/msbuild-project-tools-server/pull/58
Closes: https://github.com/tintoy/msbuild-project-tools-server/pull/48
Closes: https://github.com/tintoy/msbuild-project-tools-server/pull/46
Closes: https://github.com/tintoy/msbuild-project-tools-server/pull/44
=> Bump NuGet libraries versions to avoid security warning

src/LanguageServer/Program.cs
We can avoid splitting sync and async parts of `Main` method and use async `Main` directly
=> Use async Main entrypoint

src/LanguageServer.Common/Utilities/MSBuildHelper.cs
- Ensure file stream is closed as soon as the contents have been read
- Use FileShare.Read to enable simultaneous read-access by other processes
Fixes: tintoy/msbuild-project-tools-server#82
=> Improve file-access behaviour for project.assets.json

src/LanguageServer.Common/LanguageServer.Common.csproj, src/LanguageServer.Common/Utilities/MSBuildHelper.cs, src/LanguageServer/LanguageServer.csproj, test/LanguageServer.Engine.Tests/MSBuildEngineFixture.cs
During my investigation of https://github.com/tintoy/msbuild-project-tools-vscode/issues/89 I found out that we _need_ newer version of `MSBuild.Locator` library. I decided that it is better to separate this change in its own PR
=> Update MSBuild locator to the latest version

src/LanguageServer.Common/LanguageServer.Common.csproj, src/LanguageServer.Engine/LanguageServer.Engine.csproj, src/LanguageServer.SemanticModel.MSBuild/LanguageServer.SemanticModel.MSBuild.csproj, src/LanguageServer/LanguageServer.csproj
Closes https://github.com/tintoy/msbuild-project-tools-server/pull/97
Closes https://github.com/tintoy/msbuild-project-tools-server/pull/96
Closes https://github.com/tintoy/msbuild-project-tools-server/pull/95
- Bumped version of primary NuGet dependencies to `6.0.6` to adress dependabot alerts
- It turned out `NuGet.PackageManagement` includes all other packages as transitive dependencies, so we don't need to explicitly list them
- Removed `NuGet.Client` dependency since we don't use it and the package itself [is considered obsolete](https://www.nuget.org/packages/NuGet.Client/4.3.0-beta1-2418)
=> Remove obsolete/unnecessary NuGet dependencies and bump version of remaining ones

GitVersion.yml, src/LanguageServer.Engine/Documents/MasterProjectDocument.cs, src/LanguageServer.Engine/Documents/Workspace.cs, test/LanguageServer.Engine.Tests/LanguageServer.Engine.Tests.csproj, test/LanguageServer.Engine.Tests/MSBuildEngineFixture.cs, test/LanguageServer.Engine.Tests/MSBuildObjectLocatorTests.cs, test/LanguageServer.Engine.Tests/TestProject.cs, test/LanguageServer.Engine.Tests/TestProjects/RedefineProperty.SameFile.csproj
Relates to #100, but it turns out the actual issue is related to concurrent loads of sub-projects, not overridden properties.
=> Improve handling of concurrent loads for MSBuild sub-projects

src/LanguageServer.Common/Utilities/DotNetRuntimeInfo.cs, src/LanguageServer.Common/Utilities/DotnetInfo.cs, src/LanguageServer.Common/Utilities/MSBuildHelper.cs, src/LanguageServer.Engine/Documents/ProjectDocument.cs, test/LanguageServer.Engine.Tests/TaskScannerTests.cs
Improve behaviour of .NET version detection when the .NET host cannot resolve a matching runtime or SDK for `global.json`.
The `dotnet` host has many known exit codes, but currently only a couple are currently of interest to us. I have nevertheless included all known exit codes in an enum since the exit-code names (rather than just hex numbers) are quite likely to aid future troubleshooting efforts.,
This PR only partially addresses tintoy/msbuild-project-tools-vscode#156 (the language server side), although, since VSCode's language client doesn't provide access to the process exit code, it's challenging (for the extension side) to reliably return user-facing error messages from the language server (in scenarios like this that occur before the LSP connection has been established).
We …
=> Validate dotnet process exit code when discovering .NET SDK / runtime info

src/LanguageServer.Engine/CompletionProviders/CompletionProvider.cs
In this scenario, the last character typed is implicitly treated as part of the current selection, if it triggered completion.
tintoy/msbuild-project-tools-vscode#93
=> Correctly handle VSCode/LSP completion behaviour when triggered by one or more trigger characters

src/LanguageServer.Engine/Configuration.cs, src/LanguageServer.Engine/Documents/ProjectDocument.cs
This is the language-server component of tintoy/msbuild-project-tools-vscode#166:
Add a configuration option `Configuration.MSBuild.GlobalProperties` used to configure overrides of the default MSBuild properties used before a project is loaded. These overrides are then used when initialising the root MSBuild `ProjectCollection` that all projects are loaded into.
Note that, by design, this option is selectively overridden by more-specific property overrides (such as `Configuration.MSBuild.ExtensionsPath` and `Configuration.MSBuild.ExtensionsPath32`).
=> Initial support for overriding global MSBuild properties
